#define WIFIID       "YOUR WIFI NETWORK HERE"
#define WIFIPASS     "YOUR WIFI PASSWORD HERE"
#define CLIENTID     "APPLICATION'S CLIENT ID HERE"
#define CLIENTSECRET "APPLICATION'S CLIENT SECRET HERE"